### ISSUE TITLE
Create a `Icon` class for jewel that contains both path and the class.

### ISSUE THREAD

**Issue by lamba92** [JetBrains/jewel#271] opened 2023-12-12 09:15 UTC
We should also generate a Jewel icon object starting from known icons from the platform and icons put inside `src/main/resources/icons/**.svg/png`. We can use a Gradle Plugin inside our repo and a gradle plugin to be used by our users.

**Comment by rock3r** [comment] 2024-01-05 10:42
Duplicate of #73

**Closed by rock3r** 2024-01-05 10:42 UTC
Labels: feature, api, bridge
