### ISSUE TITLE
TextArea placeholder aliment issue

### ISSUE THREAD

**Issue by hamen** [JetBrains/jewel#614] opened 2024-09-30 09:24 UTC
![image](https://github.com/user-attachments/assets/a9432e47-3bba-4f60-b12b-37771f8bece2)
![image](https://github.com/user-attachments/assets/c85c9aa6-ab0a-4cd8-9d86-4b4cf59bcd99)

**Comment by rock3r** [comment] 2024-09-30 09:24
Dupe of #613

**Closed** 2024-09-30 09:24 UTC
Labels: bug
