### ISSUE TITLE
TitleBar sometimes not filling full window size with non regular display scaling

### ISSUE THREAD

**Issue by Goregius** [JetBrains/jewel#248] opened 2023-11-16 03:38 UTC
When the display scaling in Windows (10) is 125%, 150% or 175%. there appears to be a thin white bar on the top and right of the window. As the window is resized, one or both white bars may disappear/reappear. This was tested on 1440p and 2560p monitors.

The following screenshot is taken with the sample standalone app, with the contents of `TitleBarView` set using an empty `TitleBar`.

![image](https://github.com/JetBrains/jewel/assets/20602676/b005d297-a00e-4f40-a43d-4824a50bf109)

When the `TitleBar` composable is removed, the issue is no longer present.

**Comment by devkanro** [comment] 2024-02-17 12:10
Can't reproduce it on my windows, will try to experiment on more devices

**Comment by Goregius** [comment] 2024-02-21 13:26
I think this is an issue with the JetBrains Runtime itself, I get the same issue with Jetbrains Fleet as well. Did you try running it at 150% scaling in Windows? This is on Windows 10, so it might not be an issue on Windows 11.

**Comment by devkanro** [comment] 2024-02-22 02:19
Ohhh, I just test in Window11, I will mark it as a external issue, can you fire a issue on [JetbrainsRuntime](https://github.com/JetBrains/JetBrainsRuntime)?

**Comment by rock3r** [comment] 2024-07-23 12:41
@Goregius can you still reproduce the issue on the _latest_ JBR 17 and/or 21?

**Comment by rock3r** [comment] 2024-08-12 13:43
I'll close this since we had no answer in 3 weeks.

**Closed by rock3r** 2024-08-12 13:43 UTC
Labels: bug, blocked-externally, needs-info
